Cienciometrico/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout_then_login,password_reset,password_reset_done,password_reset_confirm,password_reset_complete
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.HomePrincipal.urls', namespace="indexHome")),
    url(r'^pais/', include('apps.pais.urls', namespace="pais")),
    url(r'^zona/', include('apps.zona.urls', namespace="zona")),
    url(r'^provincia/', include('apps.provincia.urls', namespace="provincia")),
    url(r'^ciudad/', include('apps.ciudad.urls', namespace="ciudad")),
    #url(r'^universidad/', include('apps.universidad.urls', namespace="universidad")),
    url(r'^Carrera/', include('apps.carrera.urls', namespace="carrera")),
    url(r'^Facultad/', include('apps.facultad.urls', namespace="Facultad")),
    url(r'^campus/', include('apps.campus.urls', namespace="campus")),
    url(r'^investigador/', include('apps.Investigador.urls', namespace="usuario")),
    url(r'^articulo/', include('apps.Articulos_Cientificos.urls', namespace="articulosCientificos")),
    url(r'^investigacion/', include('apps.investigaciones.urls', namespace="investigacion")),
    url(r'^datosprofesionales/', include('apps.datosprofesionales.urls', namespace="datosprofe")),
    url(r'^formacionAcad/', include('apps.Formacion_Academica.urls', namespace="FormacionAcademica")),
    url(r'^formacionComple/', include('apps.Formacion_Complementaria.urls', namespace="FormacionComplementaria")),
    url(r'^Evento/', include('apps.Evento.urls', namespace="evento")),
    url(r'^otrainvestigacion/', include('apps.otrasinvestigaciones.urls', namespace="otrainvestigacion")),
    url(r'^participacioneventos/linea', include('apps.participacioneventos.urls', namespace="partevento")),
    url(r'^proyectos/', include('apps.Proyectos.urls', namespace="proyecto")),
    url(r'^roles/', include('apps.roles.urls', namespace="roles")),
    url(r'^index/', include('apps.inicio.urls', namespace="inicio")),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^accounts/login/', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^libro/', include('apps.Libro.urls', namespace="Libro")),
    url(r'^revista/', include('apps.Revista.urls', namespace="Revista")),
    url(r'^Publicaciones/', include('apps.Publicaciones.urls', namespace="publicaciones")),
    url(r'^ponencia/', include('apps.Ponencia.urls', namespace="Ponencia")),
    url(r'^capacitacion/', include('apps.capacitacion.urls', namespace="capacitacion")),
    url(r'^intereses/', include('apps.Intereses_Formativos.urls', namespace="interes")),
    url(r'^palabras/', include('apps.palabraClave.urls', namespace="pal")),
    url(r'^db/', include('apps.baseDatos.urls', namespace="base")),
    url(r'^autor/', include('apps.autoresArticulos.urls', namespace="autor")),
    url(r'^linea/', include('apps.Linea_Investigacion.urls', namespace="linea")),
    #///////////////////////PASSWORD RESET///////////////////////////////////////
    url(r'^password_reset/', password_reset,
       {'template_name': 'registration/password_reset_form.html',
   'email_template_name': 'registration/password_reset_email.html'},
     name='password_reset'),
    url(r'^password_reset_done/', password_reset_done,
       {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_listo'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_completado'),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/inicio/urls.py
from apps.inicio.views import inicio
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
urlpatterns = [
        url(r'^$',login_required(inicio), name="logeo"),
    ]

apps/zona/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.zona.models import zona
from apps.zona.views import ZonaCreate,ZonaList,ZonaDelete,ZonaUpdate
from django.contrib.auth.decorators import login_required
urlpatterns = [
    url(r'^nuevo',login_required(ZonaCreate.as_view()), name='zona_crear'),
    url(r'^listar',login_required(ZonaList.as_view(queryset= zona.objects.all().order_by('id'))), name='zona_listar'),
    url(r'^editar/(?P<pk>\d+)/$',login_required(ZonaUpdate.as_view()), name='zona_editar'),
    url(r'^eliminar/(?P<pk>\d+)/$',login_required(ZonaDelete.as_view()), name='zona_eliminar'),
]

apps/zona/models.py
from django.db import models
from apps.pais.models import pais
# Create your models here.
class zona (models.Model):
    Nombre=models.CharField(max_length=150)
    Descripcion=models.TextField()
    pais = models.ForeignKey(pais, null=True, blank=True, on_delete=models.CASCADE)
    def __str__(self):
        return '{}'.format(self.Nombre)

    class Meta:
        permissions = (
            ("ver_zona", "ver zona"),
        )

apps/zona/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from apps.zona.form import ZonaForm
from apps.zona.models import zona
from django.views.generic import ListView, CreateView,UpdateView,DeleteView
from apps.Investigador.models import Investigador
from apps.roles.models import Rol
# Create your views here.
class ZonaList(ListView):
    model = zona
    template_name='zona/zona_listar.html'
    paginate_by = 6
    def get_context_data(self, **kwargs):
        context = super(ZonaList, self).get_context_data(**kwargs)
        usuario = self.request.user.id
        perfil = Investigador.objects.get(user_id=usuario)
        roles = perfil.roles.all()
        privi = []
        privilegios = []
        privilegio = []
        for r in roles:
            privi.append(r.id)
        for p in privi:
            roles5 = Rol.objects.get(pk=p)
            priv = roles5.privilegios.all()
            for pr in priv:
                privilegios.append(pr.codename)
        for i in privilegios:
            if i not in privilegio:
                privilegio.append(i)
        context['usuario'] = privilegio
        return context

class ZonaCreate(CreateView):
    model = zona
    form_class = ZonaForm
    template_name = 'zona/zona_crear.html'
    success_url = reverse_lazy('zona:zona_listar')
    def get_context_data(self, **kwargs):
        context = super(ZonaCreate, self).get_context_data(**kwargs)
        usuario = self.request.user.id
        perfil = Investigador.objects.get(user_id=usuario)
        roles = perfil.roles.all()
        privi = []
        privilegios = []
        privilegio = []
        for r in roles:
            privi.append(r.id)
        for p in privi:
            roles5 = Rol.objects.get(pk=p)
            priv = roles5.privilegios.all()
            for pr in priv:
                privilegios.append(pr.codename)
        for i in privilegios:
            if i not in privilegio:
                privilegio.append(i)
        context['usuario'] = privilegio
        return context
class ZonaUpdate(UpdateView):
    model = zona
    form_class = ZonaForm
    template_name = 'zona/zona_update.html'
    success_url = reverse_lazy('zona:zona_listar')
    def get_context_data(self, **kwargs):
        context = super(ZonaUpdate, self).get_context_data(**kwargs)
        usuario = self.request.user.id
        perfil = Investigador.objects.get(user_id=usuario)
        roles = perfil.roles.all()
        privi = []
        privilegios = []
        privilegio = []
        for r in roles:
            privi.append(r.id)
        for p in privi:
            roles5 = Rol.objects.get(pk=p)
            priv = roles5.privilegios.all()
            for pr in priv:
                privilegios.append(pr.codename)
        for i in privilegios:
            if i not in privilegio:
                privilegio.append(i)
        context['usuario'] = privilegio
        return context
class ZonaDelete(DeleteView):
    model = zona
    template_name = 'zona/zona_delete.html'
    success_url = reverse_lazy('zona:zona_listar')
    def get_context_data(self, **kwargs):
        context = super(ZonaDelete, self).get_context_data(**kwargs)
        usuario = self.request.user.id
        perfil = Investigador.objects.get(user_id=usuario)
        roles = perfil.roles.all()
        privi = []
        privilegios = []
        privilegio = []
        for r in roles:
            privi.append(r.id)
        for p in privi:
            roles5 = Rol.objects.get(pk=p)
            priv = roles5.privilegios.all()
            for pr in priv:
                privilegios.append(pr.codename)
        for i in privilegios:
            if i not in privilegio:
                privilegio.append(i)
        context['usuario'] = privilegio
        return context

templates/zona/zona_crear.html
{% extends 'base1/inicio.html' %}
{% load staticfiles %}

{% block subtitle %} 
    NUEVA <span style="color:#FC9C30">ZONA</span> 
    <!-- Button trigger modal -->
{% endblock%}


{% block home %}
<li class="nav-item">
    <li><a href="{% url 'inicio:logeo' %}" class="nav-link"><i class="batch-icon batch-icon-browser-alt"></i> <span>Inicio</span></a>
</li>
{% endblock %}
{% block zona %}
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'zona:zona_listar' %}">
            <i class="batch-icon batch-icon-star"></i>
            Zona
        </a>
    </li>
{% endblock %}
{% block content %}
    <div class="col-md-8">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-12 pb-5">
						<form method="post">
						    {% csrf_token %}
							<div class="row">
								<div class="col-lg-12">
									<div class="form-group">
										<label for="{{form.pais.Nombre}}">{{form.pais.label}}</label>
										{{form.pais}}
									</div>
								</div>
							</div>
						    <div class="row">
								<div class="col-lg-12">
									<div class="form-group">
										<label>Nombre</label>
										<input class="form-control" class="validate" type="text" name="Nombre">
									</div>
								</div>
							</div>
						    <div class="row">
								<div class="col-lg-12">
									<div class="form-group">
										<label>Descripción</label>
										<textarea name="Descripcion" class="form-control"></textarea>
									</div>
								</div>
							</div>

							<div class="row">
								<div class="col-lg-12">
									<div class="form-group">
										<button class="btn btn-primary "type="submit">Guardar</button>
										<a class="btn btn-default" href="{% url 'zona:zona_listar' %}">Cancelar</a>
									</div>
								</div>
							</div>

						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/zona/zona_delete.html
{% extends 'base1/inicio.html' %}
{% load staticfiles %}
{% block subtitle %} 
    Eliminar <span style="color:#FC9C30">ZONA</span> 
    <!-- Button trigger modal -->
{% endblock%}
{% block extrastatic %}
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   <link rel="stylesheet" href="static/css/animate.min.css">
{% endblock %}
 {% block home %}
    <a href="{% url 'inicio:logeo' %}"  class=" w3-bar-item w3-button"><img width="15%" src="{% static 'images/home.png' %}"> Home</a>
    {% endblock %}
 {% block zona %}
            <a href="{% url 'zona:zona_listar' %}" id="uno"class="w3-bar-item w3-button"><img width="15%" src="{% static 'images/iconos-zona.png' %}"> Zona</a>
			{% endblock %}

{% block content %}
<br>
<form method="post">
    {% csrf_token %}
    <h4>¿Desea eliminar el registro de {{object.Nombre}}?</h4>
    <button class="btn btn-danger" type="submit">Si, eliminar</button>
    <a class="btn btn-default" href="{% url 'zona:zona_listar' %}">Cancelar</a>
</form>
{% endblock %}

templates/zona/zona_listar.html
{% extends 'base1/inicio.html' %}
{% load staticfiles %}
    {% block subtitle %} 
        LISTADO DE <span style="color:#FC9C30">ZONAS</span> 
        <!-- Button trigger modal -->
        
        <a href="{% url 'zona:zona_crear' %}" class="btn btn-success  pull-right "><i class="glyphicon glyphicon-plus"></i> Nueva Zona</a>
    {% endblock%}

    
    {% block home %}
    <li class="nav-item">
        <li><a href="{% url 'inicio:logeo' %}" class="nav-link"><i class="batch-icon batch-icon-browser-alt"></i> <span>Inicio</span></a>
    </li>
    {% endblock %}
    {% block zona %}
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'zona:zona_listar' %}">
                <i class="batch-icon batch-icon-star"></i>
                Zona
            </a>
        </li>
    {% endblock %}
    {% block content %}
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-12 pb-5">
                            <div class="table-responsive">
                                <table id="datatable-1" class="table table-datatable table-striped table-hover">
                                	<thead>
                                		<tr>
                                			<td >#</td>
                                			<td style="text-align:left; width:25%;">Nombre</td>
                                            <td style="text-align:left; width:25%;">Descripción</td>
                                			<td style="text-align:left; width:25%;">País</td>
                                			<td>Acciones</td>
                                		</tr>
                                		
                                	</thead>
                                	<tbody>
                                        {% if object_list %}
                                        {% for zona in object_list %}
                                        <tr>
                                            <td>{{zona.id}}</td>
                                            <td>{{zona.Nombre}}</td>
                                            <td>{{zona.Descripcion}}</td>
                                            <td>{{ zona.pais.Nombre }}</td>
                                            <td>
                                                 <a class="btn btn-primary btn-sm" href="{% url 'zona:zona_editar' zona.id %}"><span class="glyphicon glyphicon-pencil"></span> Editar</a>
                                                <a class="btn btn-primary btn-sm" href="{% url 'zona:zona_eliminar' zona.id %}"><span class="glyphicon glyphicon-trash"></span> Eliminar</a>
                                            </td>
                                        </tr>
                                        {% endfor %}

                                        {% else %}
                                        <h4>No hay registros de Zonas</h4>
                                        {% endif %}

                                	</tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </li>
        

{% endblock%}

{% block scripts %}
    <!-- Datatables -->
    <script type="text/javascript" src="{% static 'assets/plugins/datatables/js/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/plugins/datatables/js/dataTables.bootstrap4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/plugins/datatables/js/dataTables.responsive.min.js' %}"></script>
    <!-- <script type="text/javascript" src="{% static 'assets/plugins/datatables/js/responsive.bootstrap4.min.js' %}"></script> -->
{% endblock %}

templates/zona/zona_update.html
{% extends 'base1/inicio.html' %}
{% load staticfiles %}
{% block subtitle %} 
    ACTUALIZAR <span style="color:#FC9C30">ZONA</span> 
    <!-- Button trigger modal -->
{% endblock%}
{% block home %}
<li class="nav-item">
    <li><a href="{% url 'inicio:logeo' %}" class="nav-link"><i class="batch-icon batch-icon-browser-alt"></i> <span>Inicio</span></a>
</li>
{% endblock %}
{% block zona %}
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'zona:zona_listar' %}">
            <i class="batch-icon batch-icon-star"></i>
            Zona
        </a>
    </li>
{% endblock %}
{% block content %}
	<div class="col-md-8">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-12 pb-5">
						<form method="post">
						    {% csrf_token %}
						    
						    <div class="container">
								<div class="col-md-12">
							
								</div>
								</div>
						    <div class="row">
								<div class="col-md-12">
									<div class="form-group">
										<label>Nombre</label>
										<input class="form-control" type="text" name="Nombre" value="{{zona.Nombre}}">
									</div>
								</div>
							</div>
						    <div class="row">
								<div class="col-md-8 col-md-offset-2">
									<div class="form-group">
										<label>Descripción</label>
										<textarea name="Descripcion" class="form-control">{{zona.Descripcion}}</textarea>
									</div>
								</div>
							</div>
						  	<div class="row">
								<div class="col-md-12">
									<div class="form-group">
										<label for="{{form.pais.Nombre}}">{{form.pais.label}}</label>
										{{form.pais}}
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-12">
									<div class="form-group">
										<button class="btn btn-primary "type="submit">Guardar</button>
										<a class="btn btn-default" href="{% url 'zona:zona_listar' %}">Cancelar</a>
									</div>
								</div>
							</div>

						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}