Cienciometrico/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout_then_login,password_reset,password_reset_done,password_reset_confirm,password_reset_complete
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.HomePrincipal.urls', namespace="indexHome")),
    url(r'^pais/', include('apps.pais.urls', namespace="pais")),
    url(r'^zona/', include('apps.zona.urls', namespace="zona")),
    url(r'^provincia/', include('apps.provincia.urls', namespace="provincia")),
    url(r'^ciudad/', include('apps.ciudad.urls', namespace="ciudad")),
    #url(r'^universidad/', include('apps.universidad.urls', namespace="universidad")),
    url(r'^Carrera/', include('apps.carrera.urls', namespace="carrera")),
    url(r'^Facultad/', include('apps.facultad.urls', namespace="Facultad")),
    url(r'^campus/', include('apps.campus.urls', namespace="campus")),
    url(r'^investigador/', include('apps.Investigador.urls', namespace="usuario")),
    url(r'^articulo/', include('apps.Articulos_Cientificos.urls', namespace="articulosCientificos")),
    url(r'^investigacion/', include('apps.investigaciones.urls', namespace="investigacion")),
    url(r'^datosprofesionales/', include('apps.datosprofesionales.urls', namespace="datosprofe")),
    url(r'^formacionAcad/', include('apps.Formacion_Academica.urls', namespace="FormacionAcademica")),
    url(r'^formacionComple/', include('apps.Formacion_Complementaria.urls', namespace="FormacionComplementaria")),
    url(r'^Evento/', include('apps.Evento.urls', namespace="evento")),
    url(r'^otrainvestigacion/', include('apps.otrasinvestigaciones.urls', namespace="otrainvestigacion")),
    url(r'^participacioneventos/linea', include('apps.participacioneventos.urls', namespace="partevento")),
    url(r'^proyectos/', include('apps.Proyectos.urls', namespace="proyecto")),
    url(r'^roles/', include('apps.roles.urls', namespace="roles")),
    url(r'^index/', include('apps.inicio.urls', namespace="inicio")),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^accounts/login/', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^libro/', include('apps.Libro.urls', namespace="Libro")),
    url(r'^revista/', include('apps.Revista.urls', namespace="Revista")),
    url(r'^Publicaciones/', include('apps.Publicaciones.urls', namespace="publicaciones")),
    url(r'^ponencia/', include('apps.Ponencia.urls', namespace="Ponencia")),
    url(r'^capacitacion/', include('apps.capacitacion.urls', namespace="capacitacion")),
    url(r'^intereses/', include('apps.Intereses_Formativos.urls', namespace="interes")),
    url(r'^palabras/', include('apps.palabraClave.urls', namespace="pal")),
    url(r'^db/', include('apps.baseDatos.urls', namespace="base")),
    url(r'^autor/', include('apps.autoresArticulos.urls', namespace="autor")),
    url(r'^linea/', include('apps.Linea_Investigacion.urls', namespace="linea")),
    #///////////////////////PASSWORD RESET///////////////////////////////////////
    url(r'^password_reset/', password_reset,
       {'template_name': 'registration/password_reset_form.html',
   'email_template_name': 'registration/password_reset_email.html'},
     name='password_reset'),
    url(r'^password_reset_done/', password_reset_done,
       {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_listo'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_completado'),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/Evento/urls.py
from django.conf.urls import url
from apps.Evento.models import evento
from apps.Evento.views import CreateEvento,ListEvento,UpdateEvento,DeleteEvento
from django.contrib.auth.decorators import login_required
urlpatterns = [

    url(r'^CrearEvento$',login_required(CreateEvento.as_view()), name="create_Evento"),
   url(r'^ListarEvento',login_required(ListEvento.as_view(queryset=evento.objects.all().order_by('id'))), name="lista_Evento"),
   url(r'^UpdateEvento/(?P<pk>\d+)/$',login_required(UpdateEvento.as_view()), name="update_Evento"),
   url(r'^DeleteEvento/(?P<pk>\d+)/$',login_required(DeleteEvento.as_view()), name="delete_Evento"),

]

apps/inicio/urls.py
from apps.inicio.views import inicio
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
urlpatterns = [
        url(r'^$',login_required(inicio), name="logeo"),
    ]

apps/Evento/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class evento(models.Model):
    Nombre=models.CharField(max_length=250,null=True)
    Lugar=models.CharField(max_length=250,null=True)
    Fecha=models.DateField(null=True)

    def __str__(self): return '{}'.format(self.Nombre)
    
    class Meta:
        permissions = (
            ("ver_evento", "ver evento"),
        )

apps/Evento/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from apps.Evento.models import evento
from apps.Evento.form import EventoForm
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView,ListView,UpdateView,DeleteView
from apps.Investigador.models import Investigador
from apps.roles.models import Rol
# Create your views here.

class CreateEvento (CreateView):
    model = evento
    form_class = EventoForm
    template_name = 'Evento/CreateEvento.html'
    success_url = reverse_lazy('evento:lista_Evento')
    def get_context_data(self, **kwargs):
        context = super(CreateEvento, self).get_context_data(**kwargs)
        usuario = self.request.user.id
        perfil = Investigador.objects.get(user_id=usuario)
        roles = perfil.roles.all()
        privi = []
        privilegios = []
        privilegio = []
        for r in roles:
            privi.append(r.id)
        for p in privi:
            roles5 = Rol.objects.get(pk=p)
            priv = roles5.privilegios.all()
            for pr in priv:
                privilegios.append(pr.codename)
        for i in privilegios:
            if i not in privilegio:
                privilegio.append(i)
        context['usuario'] = privilegio
        return context


class ListEvento(ListView):
    model = evento
    template_name = 'Evento/ListEvento.html'
    def get_context_data(self, **kwargs):
        context = super(ListEvento, self).get_context_data(**kwargs)
        usuario = self.request.user.id
        perfil = Investigador.objects.get(user_id=usuario)
        roles = perfil.roles.all()
        privi = []
        privilegios = []
        privilegio = []
        for r in roles:
            privi.append(r.id)
        for p in privi:
            roles5 = Rol.objects.get(pk=p)
            priv = roles5.privilegios.all()
            for pr in priv:
                privilegios.append(pr.codename)
        for i in privilegios:
            if i not in privilegio:
                privilegio.append(i)
        context['usuario'] = privilegio
        return context
class UpdateEvento (UpdateView):
    model = evento
    form_class = EventoForm
    template_name = 'Evento/UpdateEvento.html'
    success_url = reverse_lazy ('evento:lista_Evento')
    def get_context_data(self, **kwargs):
        context = super(UpdateEvento, self).get_context_data(**kwargs)
        usuario = self.request.user.id
        perfil = Investigador.objects.get(user_id=usuario)
        roles = perfil.roles.all()
        privi = []
        privilegios = []
        privilegio = []
        for r in roles:
            privi.append(r.id)
        for p in privi:
            roles5 = Rol.objects.get(pk=p)
            priv = roles5.privilegios.all()
            for pr in priv:
                privilegios.append(pr.codename)
        for i in privilegios:
            if i not in privilegio:
                privilegio.append(i)
        context['usuario'] = privilegio
        return context

class DeleteEvento (DeleteView):
    model = evento
    template_name = 'Evento/DeleteEvento.html'
    success_url = reverse_lazy('evento:lista_Evento')
    def get_context_data(self, **kwargs):
        context = super(DeleteEvento, self).get_context_data(**kwargs)
        usuario = self.request.user.id
        perfil = Investigador.objects.get(user_id=usuario)
        roles = perfil.roles.all()
        privi = []
        privilegios = []
        privilegio = []
        for r in roles:
            privi.append(r.id)
        for p in privi:
            roles5 = Rol.objects.get(pk=p)
            priv = roles5.privilegios.all()
            for pr in priv:
                privilegios.append(pr.codename)
        for i in privilegios:
            if i not in privilegio:
                privilegio.append(i)
        context['usuario'] = privilegio
        return context

templates/evento/Createevento.html
{% extends 'base1/inicio.html'%}
{% load staticfiles %}
{% block subtitle %}
    NUEVO <span style="color:#FC9C30">evento</span>

{% endblock%}
{% block home %}
<li class="nav-item">
    <li><a href="{% url 'inicio:logeo' %}" class="nav-link"><i class="batch-icon batch-icon-browser-alt"></i> <span>Inicio</span></a>

</li>
{% endblock %}

{% block evento %}
<li class="nav-item">
	<a class="nav-link active" href="{% url 'evento:lista_Evento' %}">
		<i class="batch-icon batch-icon-paper-roll-ripped"></i>
		Evento
	</a>
</li>
{% endblock %}
{% block content %}
	<div class="col-md-8">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-12 pb-5">
						 <form method="post">
								{% csrf_token %}

								<div class="row">
									<div class="col-md-12">
										{{ form.as_p }}
									</div>
								</div>
								<div class="row">
								<div class="col-md-8 col-md-offset-2">
									<div class="form-group">
										<button type="submit"   class="btn btn-primary" >Guardar</button>
									</div>
								</div>
								</div>

						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/evento/Deleteevento.html
{% extends 'base1/inicio.html'%}
{% load staticfiles %}
{% block subtitle %}
    Eliminar <span style="color:#FC9C30">evento</span>

{% endblock%}
{% block home %}
<li class="nav-item">
    <li><a href="{% url 'inicio:logeo' %}" class="nav-link"><i class="batch-icon batch-icon-browser-alt"></i> <span>Inicio</span></a>

</li>
{% endblock %}

{% block evento %}
<li class="nav-item">
	<a class="nav-link active" href="{% url 'evento:lista_Evento' %}">
		<i class="batch-icon batch-icon-paper-roll-ripped"></i>
		Evento
	</a>
</li>
{% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <br><br>
    <h1>¿Desea eliminar el registro de {{object.Nombre}} ?</h1>
    <button class="btn btn-danger" type="submit">Si, eliminar</button>
    <a class="btn btn-default" href="{% url 'evento:lista_Evento' %}">Cancelar</a>
</form>
{% endblock %}

templates/evento/Listevento.html
{% extends 'base1/inicio.html'%}
{% load staticfiles %}
{% block subtitle %}
    listado de <span style="color:#FC9C30">eventos</span>
<a href="{% url 'evento:create_Evento' %}" class="btn btn-primary  pull-right "><span class="glyphicon glyphicon-plus"></span> Nuevo Evento</a>
{% endblock%}
{% block home %}
<li class="nav-item">
    <li><a href="{% url 'inicio:logeo' %}" class="nav-link"><i class="batch-icon batch-icon-browser-alt"></i> <span>Inicio</span></a>

</li>
{% endblock %}

{% block evento %}
<li class="nav-item">
	<a class="nav-link active" href="{% url 'evento:lista_Evento' %}">
		<i class="batch-icon batch-icon-paper-roll-ripped"></i>
		Evento
	</a>
</li>
{% endblock %}
{% block content %}
<div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-12 pb-5">
                        <div class="table-responsive">
                            {% if object_list %}
                            <table id="datatable-1" class="table table-datatable table-striped table-hover">
                                <thead >
                                    <tr>
                                        <td>#</td>
                                        <td>Nombre evento</td>
                                        <td>Lugar</td>
                                        <td>Fecha</td>
                                        <td>Acciones</td>
                                    </tr>

                                </thead>
                                <tbody>

                                    {% for evento in object_list %}
                                    <tr>
                                        <td>{{evento.id}}</td>
                                        <td>{{evento.Nombre}}</td>
                                        <td>{{evento.Lugar}}</td>
                                        <td>{{evento.Fecha}}</td>


                                        <td>
                                            <a class="btn btn-warning" href="{% url 'evento:update_Evento' evento.id %}"><span class="glyphicon glyphicon-pencil"></span>Editar</a>
                                            <a class="btn btn-danger" href="{% url 'evento:delete_Evento'  evento.id %}"><span class="glyphicon glyphicon-trash"></span>Eliminar</a>

                                        </td>
                                    </tr>
                                    {% endfor %}



                                </tbody>
                            </table>

                            {% else %}
                            <h1>No hay registros de eventos</h1>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock%}
{% block scripts %}
    <!-- Datatables -->
    <script type="text/javascript" src="{% static 'assets/plugins/datatables/js/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/plugins/datatables/js/dataTables.bootstrap4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/plugins/datatables/js/dataTables.responsive.min.js' %}"></script>
    <!-- <script type="text/javascript" src="{% static 'assets/plugins/datatables/js/responsive.bootstrap4.min.js' %}"></script> -->
{% endblock %}

templates/evento/Updateevento.html
{% extends 'base1/inicio.html'%}
{% load staticfiles %}
{% block subtitle %}
    Actualizar <span style="color:#FC9C30">evento</span>

{% endblock%}
{% block home %}
<li class="nav-item">
    <li><a href="{% url 'inicio:logeo' %}" class="nav-link"><i class="batch-icon batch-icon-browser-alt"></i> <span>Inicio</span></a>

</li>
{% endblock %}

{% block evento %}
<li class="nav-item">
	<a class="nav-link active" href="{% url 'evento:lista_Evento' %}">
		<i class="batch-icon batch-icon-paper-roll-ripped"></i>
		Evento
	</a>
</li>
{% endblock %}
{% block content %}
	<div class="col-md-8">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-12 pb-5">
						 <form method="post">
								{% csrf_token %}
								<div class="row">
									<div class="col-md-12">
										{{ form.as_p }}
									</div>
								</div>

								<div class="row">
								<div class="col-md-8 col-md-offset-2">
									<div class="form-group">
										<button type="submit"   class="btn btn-primary" >Guardar</button>
									</div>
								</div>
								</div>

						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}