Cienciometrico/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout_then_login,password_reset,password_reset_done,password_reset_confirm,password_reset_complete
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.HomePrincipal.urls', namespace="indexHome")),
    url(r'^pais/', include('apps.pais.urls', namespace="pais")),
    url(r'^zona/', include('apps.zona.urls', namespace="zona")),
    url(r'^provincia/', include('apps.provincia.urls', namespace="provincia")),
    url(r'^ciudad/', include('apps.ciudad.urls', namespace="ciudad")),
    #url(r'^universidad/', include('apps.universidad.urls', namespace="universidad")),
    url(r'^Carrera/', include('apps.carrera.urls', namespace="carrera")),
    url(r'^Facultad/', include('apps.facultad.urls', namespace="Facultad")),
    url(r'^campus/', include('apps.campus.urls', namespace="campus")),
    url(r'^investigador/', include('apps.Investigador.urls', namespace="usuario")),
    url(r'^articulo/', include('apps.Articulos_Cientificos.urls', namespace="articulosCientificos")),
    url(r'^investigacion/', include('apps.investigaciones.urls', namespace="investigacion")),
    url(r'^datosprofesionales/', include('apps.datosprofesionales.urls', namespace="datosprofe")),
    url(r'^formacionAcad/', include('apps.Formacion_Academica.urls', namespace="FormacionAcademica")),
    url(r'^formacionComple/', include('apps.Formacion_Complementaria.urls', namespace="FormacionComplementaria")),
    url(r'^Evento/', include('apps.Evento.urls', namespace="evento")),
    url(r'^otrainvestigacion/', include('apps.otrasinvestigaciones.urls', namespace="otrainvestigacion")),
    url(r'^participacioneventos/linea', include('apps.participacioneventos.urls', namespace="partevento")),
    url(r'^proyectos/', include('apps.Proyectos.urls', namespace="proyecto")),
    url(r'^roles/', include('apps.roles.urls', namespace="roles")),
    url(r'^index/', include('apps.inicio.urls', namespace="inicio")),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^accounts/login/', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^libro/', include('apps.Libro.urls', namespace="Libro")),
    url(r'^revista/', include('apps.Revista.urls', namespace="Revista")),
    url(r'^Publicaciones/', include('apps.Publicaciones.urls', namespace="publicaciones")),
    url(r'^ponencia/', include('apps.Ponencia.urls', namespace="Ponencia")),
    url(r'^capacitacion/', include('apps.capacitacion.urls', namespace="capacitacion")),
    url(r'^intereses/', include('apps.Intereses_Formativos.urls', namespace="interes")),
    url(r'^palabras/', include('apps.palabraClave.urls', namespace="pal")),
    url(r'^db/', include('apps.baseDatos.urls', namespace="base")),
    url(r'^autor/', include('apps.autoresArticulos.urls', namespace="autor")),
    url(r'^linea/', include('apps.Linea_Investigacion.urls', namespace="linea")),
    #///////////////////////PASSWORD RESET///////////////////////////////////////
    url(r'^password_reset/', password_reset,
       {'template_name': 'registration/password_reset_form.html',
   'email_template_name': 'registration/password_reset_email.html'},
     name='password_reset'),
    url(r'^password_reset_done/', password_reset_done,
       {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_listo'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_completado'),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/carrera/urls.py
from django.conf.urls import url
from apps.carrera.models import carrera
from apps.carrera.views import CreateCarrera,ListCarrera,UpdateCarrera,DeleteCarrera,Carreracrear,Carreradedit
from django.contrib.auth.decorators import login_required
urlpatterns = [

    url(r'^CrearCarrera$',login_required(Carreracrear), name="create_Carrera"),
   url(r'^ListarCarrera',login_required(ListCarrera.as_view(queryset=carrera.objects.all().order_by('id'))), name="lista_Carrera"),
   url(r'^UpdateCarrera/(?P<id_carrera>\d+)/$',login_required(Carreradedit), name="update_Carrera"),
   url(r'^DeleteCarrera/(?P<pk>\d+)/$',login_required(DeleteCarrera.as_view()), name="delete_Carrera"),

]

apps/inicio/urls.py
from apps.inicio.views import inicio
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
urlpatterns = [
        url(r'^$',login_required(inicio), name="logeo"),
    ]

apps/carrera/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from apps.facultad.models import facultad

class carrera (models.Model):
    Nombre=models.CharField(max_length=350)
    Director=models.CharField(max_length=250)
    facultad=models.ForeignKey(facultad,null=True ,blank=True,on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.Nombre)

    class Meta:
        permissions = (
            ("ver_carrera", "ver carrera"),
        )

apps/carrera/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render,redirect
from apps.carrera.models import carrera
from apps.carrera.form import CarreraForm
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView,ListView,UpdateView,DeleteView
from apps.pais.models import pais
from apps.zona.models import zona
from apps.universidad.models import universidad
from apps.campus.models import campus
from apps.facultad.models import facultad
from apps.Investigador.models import Investigador
from apps.roles.models import Rol
# Create your views here.

class CreateCarrera (CreateView):
    model = carrera
    form_class = CarreraForm
    template_name = 'carrera/Createcarrera.html'
    success_url = reverse_lazy('carrera:lista_Carrera')
    def get_context_data(self, **kwargs):
        context = super(CreateCarrera, self).get_context_data(**kwargs)
        usuario = self.request.user.id
        perfil = Investigador.objects.get(user_id=usuario)
        roles = perfil.roles.all()
        privi = []
        privilegios = []
        privilegio = []
        for r in roles:
            privi.append(r.id)
        for p in privi:
            roles5 = Rol.objects.get(pk=p)
            priv = roles5.privilegios.all()
            for pr in priv:
                privilegios.append(pr.codename)
        for i in privilegios:
            if i not in privilegio:
                privilegio.append(i)
        context['usuario'] = privilegio
        return context
class ListCarrera(ListView):
    model = carrera
    template_name = 'carrera/Listcarrera.html'
    paginate_by = 6
    def get_context_data(self, **kwargs):
        context = super(ListCarrera, self).get_context_data(**kwargs)
        usuario = self.request.user.id
        perfil = Investigador.objects.get(user_id=usuario)
        roles = perfil.roles.all()
        privi = []
        privilegios = []
        privilegio = []
        for r in roles:
            privi.append(r.id)
        for p in privi:
            roles5 = Rol.objects.get(pk=p)
            priv = roles5.privilegios.all()
            for pr in priv:
                privilegios.append(pr.codename)
        for i in privilegios:
            if i not in privilegio:
                privilegio.append(i)
        context['usuario'] = privilegio
        return context
class UpdateCarrera (UpdateView):
    model = carrera
    form_class = CarreraForm
    template_name = 'carrera/Updatecarrera.html'
    success_url = reverse_lazy ('carrera:lista_Carrera')
    def get_context_data(self, **kwargs):
        context = super(UpdateCarrera, self).get_context_data(**kwargs)
        usuario = self.request.user.id
        perfil = Investigador.objects.get(user_id=usuario)
        roles = perfil.roles.all()
        privi = []
        privilegios = []
        privilegio = []
        for r in roles:
            privi.append(r.id)
        for p in privi:
            roles5 = Rol.objects.get(pk=p)
            priv = roles5.privilegios.all()
            for pr in priv:
                privilegios.append(pr.codename)
        for i in privilegios:
            if i not in privilegio:
                privilegio.append(i)
        context['usuario'] = privilegio
        return context
class DeleteCarrera (DeleteView):
    model = carrera
    template_name = 'carrera/Deletecarrera.html'
    success_url = reverse_lazy('carrera:lista_Carrera')
    def get_context_data(self, **kwargs):
        context = super(DeleteCarrera, self).get_context_data(**kwargs)
        usuario = self.request.user.id
        perfil = Investigador.objects.get(user_id=usuario)
        roles = perfil.roles.all()
        privi = []
        privilegios = []
        privilegio = []
        for r in roles:
            privi.append(r.id)
        for p in privi:
            roles5 = Rol.objects.get(pk=p)
            priv = roles5.privilegios.all()
            for pr in priv:
                privilegios.append(pr.codename)
        for i in privilegios:
            if i not in privilegio:
                privilegio.append(i)
        context['usuario'] = privilegio
        return context
def Carreracrear(request):
    Pais = pais.objects.all()
    Zona= zona.objects.all()
    Universidad=universidad.objects.all()
    Campus=campus.objects.all()
    Facultad = facultad.objects.all()
    usuario = request.user.id
    perfil = Investigador.objects.get(user_id=usuario)
    roles = perfil.roles.all()
    privi = []
    privilegios = []
    privilegio = []
    for r in roles:
        privi.append(r.id)
    for p in privi:
        roles5 = Rol.objects.get(pk=p)
        priv = roles5.privilegios.all()
        for pr in priv:
            privilegios.append(pr.codename)
    for i in privilegios:
        if i not in privilegio:
            privilegio.append(i)
    if request.method == 'POST':
        form= CarreraForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('carrera:lista_Carrera')
    else:
        form= CarreraForm()
    return render(request,'carrera/CreateCarrera.html',{'form':form,'Pais': Pais,'Zona': Zona, 'Universidad':Universidad, 'Campus':Campus,'Facultad':Facultad, 'usuario': privilegio})
def Carreradedit(request, id_carrera):
    Pais = pais.objects.all()
    Zona = zona.objects.all()
    Universidad = universidad.objects.all()
    Campus = campus.objects.all()
    Facultad = facultad.objects.all()
    carr = carrera.objects.get(id=id_carrera)
    usuario = request.user.id
    perfil = Investigador.objects.get(user_id=usuario)
    roles = perfil.roles.all()
    privi = []
    privilegios = []
    privilegio = []
    for r in roles:
        privi.append(r.id)
    for p in privi:
        roles5 = Rol.objects.get(pk=p)
        priv = roles5.privilegios.all()
        for pr in priv:
            privilegios.append(pr.codename)
    for i in privilegios:
        if i not in privilegio:
            privilegio.append(i)
    if request.method == 'GET':
        form= CarreraForm(instance=carr)
    else:
        form = CarreraForm(request.POST, instance=carr)
        if form.is_valid():
            form.save()
        return redirect('carrera:lista_Carrera')
    return render(request, 'carrera/UpdateCarrera.html',{'form':form,'Pais': Pais,'Zona': Zona, 'Universidad':Universidad, 'Campus':Campus,'Facultad':Facultad, 'usuario': privilegio})

templates/carrera/Createcarrera.html
{% extends 'base1/inicio.html'%}
{% load staticfiles %}
{% block subtitle %} 
    NUEVA <span style="color:#FC9C30">CARRERA</span> 
    
{% endblock%}
{% block home %}
<li class="nav-item">
    <li><a href="{% url 'inicio:logeo' %}" class="nav-link"><i class="batch-icon batch-icon-browser-alt"></i> <span>Inicio</span></a>

</li>
{% endblock %}
{% block carrera %}
<li class="nav-item">
    <a class="nav-link active" href="{% url 'carrera:lista_Carrera' %}">
        <i class="batch-icon batch-icon-star"></i>
        Carrera
    </a>
</li>
{% endblock %}
	{% block extrastatic %}

<script>
        function paises() {
            document.getElementById("zona").innerHTML = "";
            var v=document.getElementById("pais").value;
            var option = document.createElement("option");
            option.text = "--SELECCIONE--";
            document.getElementById("zona").add(option);
            {% for z in  Zona%}
                var id_pais={{z.pais.id}}

                if(v==id_pais){

                    var op = document.createElement("option");
                    op.value = "{{z.pk}}";
                    op.text = "{{z.Nombre}}";
                    document.getElementById("zona").appendChild(op);
                }
            {% endfor %}

        }
		function zonas() {
            document.getElementById("universidad").innerHTML = "";
            var v=document.getElementById("zona").value;
            var option = document.createElement("option");
            option.text = "--SELECCIONE--";
            document.getElementById("universidad").add(option);
            {% for u in  Universidad%}
                var id_zona={{u.zona.id}}

                if(v==id_zona){

                    var op = document.createElement("option");
                    op.value = "{{u.pk}}";
                    op.text = "{{u.Nombre}}";
                    document.getElementById("universidad").appendChild(op);
                }
            {% endfor %}

        }
        function unicam() {
            document.getElementById("campus").innerHTML = "";
            var v=document.getElementById("universidad").value;
            var option = document.createElement("option");
            option.text = "--SELECCIONE--";
            document.getElementById("campus").add(option);
            {% for ca in  Campus %}
                var id_campus={{ca.universidad.id}}

                if(v==id_campus){

                    var op = document.createElement("option");
                    op.value = "{{ca.pk}}";
                    op.text = "{{ca.Nombre}}";
                    document.getElementById("campus").appendChild(op);
                }
            {% endfor %}

        }
        function facultadcampus() {
            document.getElementById("facultad").innerHTML = "";
            var v=document.getElementById("campus").value;
            var option = document.createElement("option");
            option.text = "--SELECCIONE--";
            document.getElementById("facultad").add(option);
            {% for ca in  Facultad %}
                var id_campus={{ca.campus.id}}

                if(v==id_campus){

                    var op = document.createElement("option");
                    op.value = "{{ca.pk}}";
                    op.text = "{{ca.Nombre}}";
                    document.getElementById("facultad").appendChild(op);
                }
            {% endfor %}


        }
    </script>
{% endblock %}

{% block content %}
    <div class="col-md-8">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-12 pb-5">
                         <form method="post">
                            {% csrf_token %}
                        	   
                        	<div class="row">
                        		<div class="col-md-12">
                        			<div class="form-group">
                        				<label>Pais</label>
                                        <select class="form-control" id="pais" onchange="paises()">
                                            <option>--Seleccione--</option>
                                            {% for p in  Pais%}
                                            <option value="{{ p.pk }}">{{p.Nombre}}</option>

                                            {% endfor %}
                                        </select>
                        			</div>
                        		</div>
                        	</div>
                        	 <div class="row">
                        		<div class="col-md-12">
                        			<div class="form-group">
                        				<label>Zona</label>
                                        <select class="form-control" id="zona" onchange="zonas()">
                                            <option>--Seleccione--</option>

                                        </select>
                        			</div>
                        		</div>
                        	</div>
                        	 <div class="row">
                        		<div class="col-md-8 col-md-offset-2">
                        			<div class="form-group">
                        				<label>Universidad</label>
                                        <select class="form-control" id="universidad" onchange="unicam()">
                                            <option>--Seleccione--</option>

                                        </select>
                        			</div>
                        		</div>
                        	</div>
                        	 <div class="row">
                        		<div class="col-md-12">
                        			<div class="form-group">
                        				<label >Campus</label>
                        				<select class="form-control" id="campus" onchange="facultadcampus()">
                                            <option>--Seleccione--</option>

                                        </select>
                        			</div>
                        		</div>
                        	</div>
                        	<div class="row">
                        		<div class="col-md-12">
                        			<div class="form-group">
                        				<label >Facultad</label>
                        				<select class="form-control" id="facultad" name="facultad" onchange="myFunction()">
                                            <option>--Seleccione--</option>

                                        </select>
                        			</div>
                        		</div>
                        	</div>
                           <div class="row">
                        		<div class="col-md-12">
                        			<div class="form-group input-field">
                        				<label>Nombre de Carrera </label>
                        				<input class="form-control" type="text" name="Nombre">
                        			</div>
                        		</div>
                        	</div>
                        	<div class="row">
                        		<div class="col-md-12">
                        			<div class="form-group input-field">
                        				<label >Director de la Carrera</label>
                        				<input class="form-control" type="text" name="Director">
                        			</div>
                        		</div>
                        	</div>



                                <div class="row">
                        		<div class="col-md-12">
                        			<div class="form-group">
                                        <button type="submit"   class="btn btn-primary" >Guardar</button>
                                        <a class="btn btn-default" href="{% url 'carrera:lista_Carrera' %}">Cancelar</a>
                                    </div>
                        		</div>
                                </div>
                        	</div>


                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/carrera/Deletecarrera.html
{% extends 'base1/inicio.html'%}
{% load staticfiles %}
{% block subtitle %} 
    ELIMINAR <span style="color:#FC9C30">CARRERAS</span> 
    
{% endblock%}
{% block home %}
<li class="nav-item">
    <li><a href="{% url 'inicio:logeo' %}" class="nav-link"><i class="batch-icon batch-icon-browser-alt"></i> <span>Inicio</span></a>

</li>
{% endblock %}
{% block carrera %}
<li class="nav-item">
    <a class="nav-link active" href="{% url 'carrera:lista_Carrera' %}">
        <i class="batch-icon batch-icon-star"></i>
        Carrera
    </a>
</li>
{% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <br><br>
    <h4>¿Desea eliminar el registro de {{object.Nombre}} ?</h4>
    <button class="btn btn-danger" type="submit">Si, eliminar</button>
    <a class="btn btn-default" href="{% url 'carrera:lista_Carrera' %}">Cancelar</a>
</form>
{% endblock %}

templates/carrera/Listcarrera.html
{% extends 'base1/inicio.html'%}
{% load staticfiles %}
{% block subtitle %} 
    LISTADO DE <span style="color:#FC9C30">CARRERAS</span> 
     <a href="{% url 'carrera:create_Carrera' %}" class="btn btn-primary  pull-right "><i class="glyphicon glyphicon-plus"></i> Nueva Carrera</a>
{% endblock%}
{% block home %}
<li class="nav-item">
    <li><a href="{% url 'inicio:logeo' %}" class="nav-link"><i class="batch-icon batch-icon-browser-alt"></i> <span>Inicio</span></a>

</li>
{% endblock %}
{% block carrera %}
<li class="nav-item">
    <a class="nav-link active" href="{% url 'carrera:lista_Carrera' %}">
        <i class="batch-icon batch-icon-star"></i>
        Carrera
    </a>
</li>
{% endblock %}

{% block content %}
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-12 pb-5">
                        <div class="table-responsive">
                            {% if object_list %}
                            <table id="datatable-1" class="table table-datatable table-striped table-hover">    
                            	<thead >
                            		<tr>
                            			<td>#</td>
                            			<td>Nombre Carrera</td>
                            			<td>Director de Carrera</td>
                            			<td>Facultad</td>
                                        <td>Acciones</td>
                            		</tr>

                            	</thead>
                            	<tbody>
                                    
                                    {% for carrera in object_list %}
                                    <tr>
                                        <td>{{carrera.id}}</td>
                                        <td>{{carrera.Nombre}}</td>
                                        <td>{{carrera.Director}}</td>
                                        <td>{{carrera.facultad.Nombre}}</td>


                                        <td>
                                            <a class="btn btn-warning btn-sm" href="{% url 'carrera:update_Carrera' carrera.id %}" ><span class="glyphicon glyphicon-pencil"></span> Editar</a>
                                            <a class="btn btn-danger btn-sm" href="{% url 'carrera:delete_Carrera'  carrera.id %}"><span class="glyphicon glyphicon-trash"></span> Eliminar</a>

                                        </td>
                                    </tr>
                                    {% endfor %}

                                    

                            	</tbody>
                            </table>
                            {% else %}
                            <h4>No hay registros de carreras</h4>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock%}

{% block scripts %}
    <!-- Datatables -->
    <script type="text/javascript" src="{% static 'assets/plugins/datatables/js/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/plugins/datatables/js/dataTables.bootstrap4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/plugins/datatables/js/dataTables.responsive.min.js' %}"></script>
    <!-- <script type="text/javascript" src="{% static 'assets/plugins/datatables/js/responsive.bootstrap4.min.js' %}"></script> -->
{% endblock %}