Cienciometrico/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout_then_login,password_reset,password_reset_done,password_reset_confirm,password_reset_complete
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.HomePrincipal.urls', namespace="indexHome")),
    url(r'^pais/', include('apps.pais.urls', namespace="pais")),
    url(r'^zona/', include('apps.zona.urls', namespace="zona")),
    url(r'^provincia/', include('apps.provincia.urls', namespace="provincia")),
    url(r'^ciudad/', include('apps.ciudad.urls', namespace="ciudad")),
    #url(r'^universidad/', include('apps.universidad.urls', namespace="universidad")),
    url(r'^Carrera/', include('apps.carrera.urls', namespace="carrera")),
    url(r'^Facultad/', include('apps.facultad.urls', namespace="Facultad")),
    url(r'^campus/', include('apps.campus.urls', namespace="campus")),
    url(r'^investigador/', include('apps.Investigador.urls', namespace="usuario")),
    url(r'^articulo/', include('apps.Articulos_Cientificos.urls', namespace="articulosCientificos")),
    url(r'^investigacion/', include('apps.investigaciones.urls', namespace="investigacion")),
    url(r'^datosprofesionales/', include('apps.datosprofesionales.urls', namespace="datosprofe")),
    url(r'^formacionAcad/', include('apps.Formacion_Academica.urls', namespace="FormacionAcademica")),
    url(r'^formacionComple/', include('apps.Formacion_Complementaria.urls', namespace="FormacionComplementaria")),
    url(r'^Evento/', include('apps.Evento.urls', namespace="evento")),
    url(r'^otrainvestigacion/', include('apps.otrasinvestigaciones.urls', namespace="otrainvestigacion")),
    url(r'^participacioneventos/linea', include('apps.participacioneventos.urls', namespace="partevento")),
    url(r'^proyectos/', include('apps.Proyectos.urls', namespace="proyecto")),
    url(r'^roles/', include('apps.roles.urls', namespace="roles")),
    url(r'^index/', include('apps.inicio.urls', namespace="inicio")),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^accounts/login/', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^libro/', include('apps.Libro.urls', namespace="Libro")),
    url(r'^revista/', include('apps.Revista.urls', namespace="Revista")),
    url(r'^Publicaciones/', include('apps.Publicaciones.urls', namespace="publicaciones")),
    url(r'^ponencia/', include('apps.Ponencia.urls', namespace="Ponencia")),
    url(r'^capacitacion/', include('apps.capacitacion.urls', namespace="capacitacion")),
    url(r'^intereses/', include('apps.Intereses_Formativos.urls', namespace="interes")),
    url(r'^palabras/', include('apps.palabraClave.urls', namespace="pal")),
    url(r'^db/', include('apps.baseDatos.urls', namespace="base")),
    url(r'^autor/', include('apps.autoresArticulos.urls', namespace="autor")),
    url(r'^linea/', include('apps.Linea_Investigacion.urls', namespace="linea")),
    #///////////////////////PASSWORD RESET///////////////////////////////////////
    url(r'^password_reset/', password_reset,
       {'template_name': 'registration/password_reset_form.html',
   'email_template_name': 'registration/password_reset_email.html'},
     name='password_reset'),
    url(r'^password_reset_done/', password_reset_done,
       {'template_name': 'registration/password_reset_done.html'},
        name='password_reset_listo'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_completado'),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/inicio/urls.py
from apps.inicio.views import inicio
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
urlpatterns = [
        url(r'^$',login_required(inicio), name="logeo"),
    ]

apps/participacioneventos/urls.py
from django.conf.urls import url
from apps.participacioneventos.models import participacionevento
from apps.participacioneventos.views import participacioneventoscrear,participacioneventosDelete,participacioneventosEdit,participacioneventosList
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^uploads/form/$', login_required(participacioneventoscrear), name='partevento_crear'),
    url(r'^listar', login_required(participacioneventosList.as_view(queryset= participacionevento.objects.all().order_by('id'))), name='partevento_lis'),
    url(r'^editar/(?P<id_participacioneventos>\d+)/$',login_required(participacioneventosEdit), name='partevento_update'),
    url(r'^eliminar/(?P<pk>\d+)/$',login_required(participacioneventosDelete.as_view()), name='partevento_eliminar'),
]

apps/participacioneventos/models.py
from django.db import models

# Create your models here.
class participacionevento(models.Model):

    Titulo = models.CharField(max_length=255)
    Nivel_Autoria=models.CharField(max_length=255)
    Palabras_Clave = models.TextField(max_length=550)
    Resumen= models.TextField(max_length=550)
    Documento = models.FileField(upload_to='eventos/', null=True, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    Nombre_Evento=models.CharField(max_length=255)
    Nivel=models.CharField(max_length=255)
    Lugar_Evento=models.CharField(max_length=255)
    Fecha_Evento=models.DateField()

    class Meta:
        permissions = (
            ("ver_ParticipacionesEventos", "ver ParticipacionesEventos"),
        )

apps/participacioneventos/views.py
from django.shortcuts import render,redirect
from django.core.urlresolvers import reverse_lazy
from apps.participacioneventos.models import participacionevento
from django.views.generic import ListView,DeleteView
from apps.participacioneventos.form import DocuForm
from apps.Investigador.models import Investigador
from apps.roles.models import Rol
# Create your views here.
def participacioneventoscrear(request):
    usuario = request.user.id
    perfil = Investigador.objects.get(user_id=usuario)
    roles = perfil.roles.all()
    privi = []
    privilegios = []
    privilegio = []
    for r in roles:
        privi.append(r.id)
    for p in privi:
        roles5 = Rol.objects.get(pk=p)
        priv = roles5.privilegios.all()
        for pr in priv:
            privilegios.append(pr.codename)
    for i in privilegios:
        if i not in privilegio:
            privilegio.append(i)
    if request.method == 'POST':
        form = DocuForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('partevento:partevento_lis')
    else:
        form = DocuForm()
    return render(request, 'participacioneventos/participacioneventos_crear.html', {
        'form': form, 'usuario': privilegio
    })
class participacioneventosList(ListView):
    model = participacionevento
    template_name = 'participacioneventos/participacioneventos_listar.html'
    paginate_by = 6
    def get_context_data(self, **kwargs):
        context = super(participacioneventosList, self).get_context_data(**kwargs)
        usuario = self.request.user.id
        perfil = Investigador.objects.get(user_id=usuario)
        roles = perfil.roles.all()
        privi = []
        privilegios = []
        privilegio = []
        for r in roles:
            privi.append(r.id)
        for p in privi:
            roles5 = Rol.objects.get(pk=p)
            priv = roles5.privilegios.all()
            for pr in priv:
                privilegios.append(pr.codename)
        for i in privilegios:
            if i not in privilegio:
                privilegio.append(i)
        context['usuario'] = privilegio
        return context
def participacioneventosEdit(request, id_participacioneventos):
    usuario = request.user.id
    perfil = Investigador.objects.get(user_id=usuario)
    roles = perfil.roles.all()
    privi = []
    privilegios = []
    privilegio = []
    for r in roles:
        privi.append(r.id)
    for p in privi:
        roles5 = Rol.objects.get(pk=p)
        priv = roles5.privilegios.all()
        for pr in priv:
            privilegios.append(pr.codename)
    for i in privilegios:
        if i not in privilegio:
            privilegio.append(i)
    pevento = participacionevento.objects.get(id=id_participacioneventos)
    if request.method == 'POST':
        form = DocuForm(request.POST, request.FILES,instance=pevento)
        if form.is_valid():
            form.save()
            return redirect('partevento:partevento_lis')
    else:
        form = DocuForm(instance=pevento)
    return render(request, 'participacioneventos/participacioneventos_update.html', {'form': form, 'usuario': privilegio})
class participacioneventosDelete(DeleteView):
    model = participacionevento
    template_name = 'participacioneventos/participacioneventos_delete.html'
    success_url = reverse_lazy('partevento:partevento_lis')
    def get_context_data(self, **kwargs):
        context = super(participacioneventosDelete, self).get_context_data(**kwargs)
        usuario = self.request.user.id
        perfil = Investigador.objects.get(user_id=usuario)
        roles = perfil.roles.all()
        privi = []
        privilegios = []
        privilegio = []
        for r in roles:
            privi.append(r.id)
        for p in privi:
            roles5 = Rol.objects.get(pk=p)
            priv = roles5.privilegios.all()
            for pr in priv:
                privilegios.append(pr.codename)
        for i in privilegios:
            if i not in privilegio:
                privilegio.append(i)
        context['usuario'] = privilegio
        return context

templates/participacioneventos/participacioneventos_crear.html
{% extends 'base1/inicio.html'%}
{% load staticfiles %}

{% block extrastatic %}
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   <link rel="stylesheet" href="static/css/animate.min.css">
{% endblock %}
    {% block home %}
    <a href="{% url 'inicio:logeo' %}"  class=" w3-bar-item w3-button"><img width="15%" src="{% static 'images/home.png' %}"> Home</a>
    {% endblock %}
    {% block item2 %}
    <a href="{% url 'partevento:partevento_lis' %}"id="uno" class="w3-bar-item w3-button"><img width="15%" src="{% static 'images/country.png' %}"> Participación en Eventos</a>
    {% endblock %}
{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="wow fadeInUp animated" style="background: #009688; height:20%;  padding: 1cm 3cm 1cm 3cm;" >
     <h2 align="center" style="color:white"><span class="glyphicon glyphicon-plus"></span> NUEVA <span style="color:#FC9C30">PARTICIPACIÓN DE EVENTOS</span> </h2>
        <div style="float:right;">
            <strong style="color:white;font-size:100%">Bienvenido/</strong>
            <strong style="color:white;font-size:100%">{{user.username}}/</strong>
            <strong style="color:white;font-size:100%"><a href="{% url 'logout'%}" style="color:white;"><span class="glyphicon glyphicon-log-out"></span>Cerrar Sesión</a></strong>
        </a>
            </div>
        </div>
    <br>
	<div class="container">
		<div class="col-md-10 col-md-offset-2">
	<a href="{% url 'partevento:partevento_lis' %}" class="btn btn-primary  pull-right"><i class="glyphicon glyphicon-eye-open"></i> Ver Todos</a>
		</div>
		</div>
    <div class="row">
		<div class="col-md-8 col-md-offset-2">
              {{form.as_p}}
        </div>
    </div>
    <div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<button class="btn btn-primary "type="submit">Guardar</button>
			</div>
		</div>
	</div>
  </form>


{% endblock %}

templates/participacioneventos/participacioneventos_delete.html
{% extends 'base1/inicio.html'%}
{% load staticfiles %}
    {% block home %}
    <a href="{% url 'inicio:logeo' %}"  class=" w3-bar-item w3-button"><img width="15%" src="{% static 'images/home.png' %}"> Home</a>
    {% endblock %}
    {% block item2 %}
    <a href="{% url 'partevento:partevento_lis' %}"id="uno" class="w3-bar-item w3-button"><img width="15%" src="{% static 'images/country.png' %}"> Participación en Eventos</a>
    {% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <br><br>
    <h1>¿Desea eliminar el registro de {{object.Titulo}} ?</h1>
    <button class="btn btn-danger" type="submit">Si, eliminar</button>
    <a class="btn btn-default" href="{% url 'partevento:partevento_lis' %}">Cancelar</a>
</form>
{% endblock %}

templates/participacioneventos/participacioneventos_listar.html
{% extends 'base1/inicio.html'%}
{% load staticfiles %}
{% block extrastatic %}
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   <link rel="stylesheet" href="static/css/animate.min.css">
{% endblock %}
    {% block home %}
    <a href="{% url 'inicio:logeo' %}"  class=" w3-bar-item w3-button"><img width="15%" src="{% static 'images/home.png' %}"> Home</a>
    {% endblock %}
    {% block item2 %}
    <a href="{% url 'partevento:partevento_lis' %}"id="uno" class="w3-bar-item w3-button"><img width="15%" src="{% static 'images/country.png' %}"> Participación en Eventos</a>
    {% endblock %}
{% block content %}
<div class="wow fadeInUp animated" style="background: #009688; height:20%;  padding: 1cm 3cm 1cm 3cm;" >
     <h4 align="center" style="color:white"><span class="glyphicon glyphicon-th-list"></span> LISTADO DE <span style="color:#FC9C30">PARTICIPACIÓN EN EVENTOS</span> </h4>
        <div style="float:right;">
            <h6><strong style="color:white;font-size:100%">Bienvenido/</strong>
            <strong style="color:white;font-size:100%">{{user.username}}/</strong>
            <strong style="color:white;font-size:100%"><a href="{% url 'logout'%}" style="color:white;"><span class="glyphicon glyphicon-log-out"></span>Cerrar Sesión</a></strong></h6>
        </a>
            </div>
        </div>
    <br>
<div class="container">
<a href="{% url 'partevento:partevento_crear' %}" class="btn btn-primary  pull-right "><i class="glyphicon glyphicon-plus"></i> Nueva Participación</a>
    </div>
<br>
<div class="table-responsive">
<table class="table table-bordered" style="text-align:center; width:100%; ">
 	<thead >
		<tr>
			<td>#</td>
			<td>Título</td>
            <td>Nivel de Autoría</td>
			<td>Palabras Claves</td>
            <td>Resumen</td>
            <td>Documento</td>
			<td>Nombre del Evento</td>
            <td>Nivel</td>
            <td>Lugar del Evento</td>
            <td>Fecha del Evento</td>
            <td>Acciones</td>
		</tr>

	</thead>
	<tbody>
        {% if object_list %}
        {% for participacionevento in object_list %}
        <tr>
            <td>{{participacionevento.id}}</td>
            <td>{{participacionevento.Titulo}}</td>
            <td>{{participacionevento.Nivel_Autoria}}</td>
            <td>{{participacionevento.Palabras_Clave}}</td>
            <td>{{participacionevento.Resumen}}</td>
            <td>
                <li>
                    <a href="{{ participacionevento.Documento.url }}">{{ participacionevento.Documento.name }}</a>
                    <small>(Uploaded at: {{ participacionevento.uploaded_at }})</small>
                </li>
            </td>
            <td>{{participacionevento.Nombre_Evento}}</td>
            <td>{{participacionevento.Nivel}}</td>
            <td>{{participacionevento.Lugar_Evento}}</td>
            <td>{{participacionevento.Fecha_Evento}}</td>
            <td>
                <a class="btn btn-warning" href="{% url 'partevento:partevento_update' participacionevento.id %}" ><span class="glyphicon glyphicon-pencil"></span> Editar</a>
                <a class="btn btn-danger" href="{% url 'partevento:partevento_eliminar' participacionevento.id %}"><span class="glyphicon glyphicon-trash"></span> Eliminar</a>

            </td>
        </tr>
        {% endfor %}

        {% else %}
        <h4>No hay registros de Participación en Eventos</h4>
        {% endif %}

	</tbody>
</table>

</div>
{% endblock%}

templates/participacioneventos/participacioneventos_update.html
{% extends 'base1/inicio.html'%}
{% load staticfiles %}
{% block extrastatic %}
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   <link rel="stylesheet" href="static/css/animate.min.css">
{% endblock %}
    {% block home %}
    <a href="{% url 'inicio:logeo' %}"  class=" w3-bar-item w3-button"><img width="15%" src="{% static 'images/home.png' %}"> Home</a>
    {% endblock %}
    {% block item2 %}
    <a href="{% url 'partevento:partevento_lis' %}"id="uno" class="w3-bar-item w3-button"><img width="15%" src="{% static 'images/country.png' %}"> Participación en Eventos</a>
    {% endblock %}
{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="wow fadeInUp animated" style="background: #009688; height:20%;  padding: 1cm 3cm 1cm 3cm;" >
     <h2 align="center" style="color:white"><span class="glyphicon glyphicon-plus"></span> ACTUALIZAR <span style="color:#FC9C30">PARTICIPACIÓN EN EVENTOS</span> </h2>
        <div style="float:right;">
            <strong style="color:white;font-size:100%">Bienvenido/</strong>
            <strong style="color:white;font-size:100%">{{user.username}}/</strong>
            <strong style="color:white;font-size:100%"><a href="{% url 'logout'%}" style="color:white;"><span class="glyphicon glyphicon-log-out"></span>Cerrar Sesión</a></strong>
        </a>
            </div>
        </div>
    <br>
    <div class="container">
		<div class="col-md-10 col-md-offset-2">
	<a href="{% url 'partevento:partevento_lis' %}" class="btn btn-primary  pull-right"><i class="glyphicon glyphicon-eye-open"></i> Ver Todos</a>
		</div>
		</div>
    <div class="row">
		<div class="col-md-8 col-md-offset-2">
           {% form form=form %}{% endform %}
        </div>
    </div>
    <div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<button class="btn btn-primary "type="submit">Guardar</button>
                <a href="{% url 'partevento:partevento_lis' %}" class="btn btn-danger"type="button">Cancelar</a>
			</div>
		</div>
	</div>
  </form>


{% endblock %}